// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb0qpO10jdhHgEYLs5rGVvcFYgFcojhvo',
    appId: '1:51898272271:web:3ace17a09b311a700c717a',
    messagingSenderId: '51898272271',
    projectId: 'memo-e7e94',
    authDomain: 'memo-e7e94.firebaseapp.com',
    storageBucket: 'memo-e7e94.appspot.com',
    measurementId: 'G-NTLS8YLGJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6bZm2uq9uE53Yh5Hp23Xqyy4e1VVIOU',
    appId: '1:51898272271:android:56415fa8481d8c340c717a',
    messagingSenderId: '51898272271',
    projectId: 'memo-e7e94',
    storageBucket: 'memo-e7e94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfstspM9onTpjIJXVolQqCXbXZntHMKOI',
    appId: '1:51898272271:ios:8ab1792fa202956f0c717a',
    messagingSenderId: '51898272271',
    projectId: 'memo-e7e94',
    storageBucket: 'memo-e7e94.appspot.com',
    iosClientId: '51898272271-tqbpvcsqf97nn14fe4orpecvdonmhnr6.apps.googleusercontent.com',
    iosBundleId: 'com.tuanquan.memo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfstspM9onTpjIJXVolQqCXbXZntHMKOI',
    appId: '1:51898272271:ios:8ab1792fa202956f0c717a',
    messagingSenderId: '51898272271',
    projectId: 'memo-e7e94',
    storageBucket: 'memo-e7e94.appspot.com',
    iosClientId: '51898272271-tqbpvcsqf97nn14fe4orpecvdonmhnr6.apps.googleusercontent.com',
    iosBundleId: 'com.tuanquan.memo',
  );
}
